# 声明版本
version: "3"
services:
  # 服务名称,并且这个服务名称能够在同一网络中
  consul-imooc:
    #说明采用的镜像地址
    image: cap1573/consul
    ports:
      - "8500:8500"

  # 链路追踪
  jaeger-imooc:
    image: cap1573/jaeger
    ports:
      - "6831:6831/udp"
      - "16686:16686"

  # 熔断器
  hystrix-dashboard:
    image: cap1573/hystrix-dashboard
    ports:
      - "9002:9002"

  # 监控
  prometheus:
    #说明采用的镜像地址
    image: prom/prometheus
    #把外部yml文件挂载到容器中
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  #熔断看板
  grafana:
    #说明采用的镜像地址
    image: grafana/grafana
    #镜像对外映射的端口
    ports:
      - "3000:3000"
